# pytorch_lightning==1.8.1
seed_everything: 42
ckpt_path: "/import/c4dm-04/yz007/base_context_batch8/checkpoints/last.ckpt"
model:
  class_path: lightning.DiffusionLM
  init_args:
    num_emb: 901
    output_dim: 128
    max_input_length: 3000
    max_output_length: 257
    emb_dim: 758
    dim_feedforward: 2048
    nhead: 12
    head_dim: 64
    num_layers: 12
    cfg_dropout: 0.1
    cfg_weighting: 0.0 #2.0
    with_context: false
    dropout: 0.1
    layer_norm_eps: 1.0e-05
    norm_first: true
    sample_rate: 16000
    n_fft: 1024
    win_length: 640
    hop_length: 320
    f_min: 0.0
    f_max: 8000.0
    pad: 0
    n_mels: 128
    power: 1.0
    normalized: false
    wkwargs: null
    center: true
    pad_mode: reflect
    onesided: true
    norm: null
    mel_scale: htk
data:
  class_path: lightning.data.ConcatData
  init_args:
    batch_size: 2
    midi_output_size: null
    with_context: true
    sample_rate: 16000
    segment_length: 81920
    musicnet_path: /import/c4dm-datasets/musicnet/
    maestro_path: /import/c4dm-datasets/maestro-v3.0.0/
    slakh_path: /import/c4dm-datasets/Slakh/slakh2100_flac_redux/
    guitarset_path: /import/c4dm-datasets/GuitarSet/
    urmp_wav_path: /import/c4dm-datasets/URMP/Dataset/
    urmp_midi_path: /import/c4dm-datasets/URMP-clean-midi/
