# pytorch_lightning==1.8.1
seed_everything: 2434
trainer:
  logger: true
  enable_checkpointing: true
  callbacks: null
  default_root_dir: null
  gradient_clip_val: null
  gradient_clip_algorithm: null
  num_nodes: 1
  num_processes: null
  devices: null
  gpus: null
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: null
  min_epochs: null
  max_steps: 500000
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  val_check_interval: null
  log_every_n_steps: 1
  accelerator: gpu
  strategy: ddp
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: null
  deterministic: null
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  inference_mode: true
ckpt_path: null
model:
  class_path: lightning.DiffusionLM
  init_args:
    num_emb: 901
    output_dim: 128
    max_input_length: 3000
    max_output_length: 257
    emb_dim: 512
    dim_feedforward: 1024
    nhead: 6
    head_dim: 64
    num_layers: 8
    cfg_dropout: 0.1
    cfg_weighting: 2.0
    with_context: true
    dropout: 0.1
    layer_norm_eps: 1.0e-05
    norm_first: true
    sample_rate: 16000
    n_fft: 1024
    win_length: 640
    hop_length: 320
    f_min: 0.0
    f_max: 8000.0
    pad: 0
    n_mels: 128
    power: 1.0
    normalized: false
    wkwargs: null
    center: true
    pad_mode: reflect
    onesided: true
    norm: null
    mel_scale: htk
data:
  class_path: lightning.data.ConcatData
  init_args:
    batch_size: 4
    midi_output_size: null
    with_context: true
    sample_rate: 16000
    segment_length: 81920
    music4all_path: /import/c4dm-04/yz007/music4all
